# Generated by Django 3.0.8 on 2020-09-04 00:00

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, upload_to=community.models.date_upload_to),
        ),
    ]
