# Generated by Django 3.0.8 on 2020-09-05 14:30

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userID', models.CharField(max_length=21, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('role', models.CharField(choices=[('1', '봉사자'), ('2', '보호소 담당자')], max_length=2)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneAuth',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰 번호')),
                ('auth_number', models.IntegerField(verbose_name='인증 번호')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=20, verbose_name='보호소 이름')),
                ('loc_short', models.CharField(default='서울특별시 종로구', max_length=15, verbose_name='간단한 주소')),
                ('loc_detail', models.CharField(blank=True, max_length=50, verbose_name='상세 주소')),
                ('url', models.URLField(blank=True, verbose_name='보호소 홍보 SNS URL')),
                ('chat_url', models.URLField(blank=True, verbose_name='보호소 오픈채팅 URL')),
                ('status', models.CharField(default='개 0마리', max_length=100, verbose_name='동물 보호 현황')),
                ('content', models.TextField(blank=True, verbose_name='보호소 소개')),
                ('caution', models.TextField(blank=True, verbose_name='봉사 주의사항')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShelterThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(null=True, upload_to=accounts.models.date_upload_to)),
                ('shelter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Shelter')),
            ],
        ),
    ]
