# Generated by Django 3.0.8 on 2020-09-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='chat_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='보호소 오픈채팅 URL'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='보호소 홍보 SNS URL'),
        ),
    ]
