# Generated by Django 3.0.8 on 2020-08-27 07:46

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='caution',
            field=models.TextField(blank=True, verbose_name='봉사 주의사항'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='content',
            field=models.TextField(blank=True, verbose_name='보호소 소개'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='chat_url',
            field=models.URLField(blank=True, verbose_name='보호소 오픈채팅 URL'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='loc_detail',
            field=models.CharField(blank=True, max_length=50, verbose_name='상세 주소'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='loc_short',
            field=models.CharField(default='서울특별시 종로구', max_length=15, verbose_name='간단한 주소'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='shelter_name',
            field=models.CharField(max_length=20, verbose_name='보호소 이름'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='status',
            field=models.CharField(default='개 0마리', max_length=100, verbose_name='동물 보호 현황'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='url',
            field=models.URLField(blank=True, verbose_name='보호소 홍보 SNS URL'),
        ),
        migrations.CreateModel(
            name='ShelterThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(null=True, upload_to=accounts.models.date_upload_to)),
                ('shelter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Shelter')),
            ],
        ),
    ]
