# Generated by Django 3.0.8 on 2021-02-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='limit_number',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
