# Generated by Django 3.0.8 on 2020-09-09 09:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200906_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='image',
            field=models.ImageField(null=True, upload_to=accounts.models.thumbnail_upload_to, verbose_name='첨부 이미지'),
        ),
        migrations.DeleteModel(
            name='ShelterThumbnail',
        ),
    ]
