# Generated by Django 3.0.8 on 2020-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200909_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='limit_of_volunteer',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
