# Generated by Django 3.0.8 on 2021-02-10 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import volunteer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecruitmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('need_number', models.PositiveIntegerField(default=9, verbose_name='필요한 인원')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='현재 인원')),
                ('applicant', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, null=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='업로드 날짜')),
                ('image', models.ImageField(null=True, upload_to=volunteer.models.date_upload_to, verbose_name='첨부 이미지')),
                ('information', models.TextField(blank=True, verbose_name='봉사 설명')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Shelter')),
                ('tags', models.ManyToManyField(to='volunteer.Tag', verbose_name='태그')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now=True)),
                ('applying_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.DailyRecruitmentStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'applying_for')},
            },
        ),
    ]
