# Generated by Django 3.0.8 on 2021-02-24 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecruitmentstatus',
            name='need_number',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 2, 47, 44, 281754, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 2, 47, 44, 281718, tzinfo=utc)),
        ),
    ]
