# Generated by Django 3.0.8 on 2020-08-31 03:12

from django.db import migrations, models
import volunteer.models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업로드 날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=volunteer.models.date_upload_to, verbose_name='첨부 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='information',
            field=models.TextField(blank=True, verbose_name='봉사 설명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='on_going',
            field=models.BooleanField(default=True, verbose_name='봉사모집 상태'),
        ),
    ]
