# Generated by Django 3.0.8 on 2020-09-04 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0002_auto_20200904_0740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservolunteer',
            unique_together={('user', 'volunteer')},
        ),
    ]
