# Generated by Django 3.0.8 on 2020-09-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20200904_0740'),
        ('volunteer', '0002_auto_20200831_1212'),
    ]

    operations = [
    ]
