# Generated by Django 3.0.8 on 2021-02-24 16:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shelter_limit_number'),
        ('volunteer', '0002_auto_20210224_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 16, 18, 27, 490477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='shelter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Shelter'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 16, 18, 27, 490441, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='tags',
            field=models.ManyToManyField(related_name='recruitment', to='volunteer.Tag', verbose_name='태그'),
        ),
    ]
