# Generated by Django 3.0.8 on 2021-02-24 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20210225_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecruitmentstatus',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 17, 2, 4, 519128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 17, 2, 4, 519101, tzinfo=utc)),
        ),
    ]
